// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    BodyContent: typeof import('./views/photo/components/BodyContent.vue')['default']
    ClassifyPhoto: typeof import('./views/photo/components/classifyPhoto.vue')['default']
    ColorButton: typeof import('./components/ColorButton/ColorButton.vue')['default']
    ExcessivePageLayout: typeof import('./layout/ExcessivePageLayout/index.vue')['default']
    Gastly: typeof import('./components/gastly/gastly.vue')['default']
    HeaderContent: typeof import('./views/photo/components/HeaderContent.vue')['default']
    HeaderFooter: typeof import('./views/photo/components/HeaderFooter.vue')['default']
    Home: typeof import('./views/music/components/Home/index.vue')['default']
    HomeSubMenu: typeof import('./views/music/components/HomeSubMenu/index.vue')['default']
    HomeTopMenu: typeof import('./views/music/components/HomeTopMenu/index.vue')['default']
    LoginLayout: typeof import('./layout/LoginLayout/index.vue')['default']
    Movie: typeof import('./views/movie/index.vue')['default']
    Music: typeof import('./views/music/index.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NotFound: typeof import('./views/not-found/not-found.vue')['default']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    Photo: typeof import('./views/photo/index.vue')['default']
    QjgInput: typeof import('./components/QjgInput/QjgInput.vue')['default']
    QjgList: typeof import('./views/music/components/Home/components/QjgList.vue')['default']
    Src: typeof import('./base-ui/carousel/src/index.vue')['default']
    Study: typeof import('./views/study/index.vue')['default']
  }
}

export {}
